permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "blog.sublime-project", "blog.sublime-workspace"]
highlighter: pygments
markdown: kramdown
kramdown:
  use_coderay: false

title : Inglourious Coder
tagline: A Coder's work is never done.
author :
  name : Amanpreet Singh
  email : aps.sids@gmail.com
  github : aps-sids
  facebook: amanz008
  twitter : aps_sids
  linkedin : amanpreet-singh/26/802/666
  google_plus : 114056544272791132056